
# Example configuration.yaml entry for Govee Light Automation integration
# Replace YOUR_GOVEE_API_KEY with your actual API key from Govee Developer Portal
govee_light_automation:
  api_key: YOUR_GOVEE_API_KEY
  # devices:
  #   - device_id: "xx:xx:xx:xx:xx:xx:xx:xx"
  #     name: "Living Room Light"

# Remove any unsupported options from inside govee_light_automation.
# Only use valid options as per the integration documentation.