# Example configuration.yaml entry for Govee Light Automation integration
# Replace YOUR_GOVEE_API_KEY with your actual API key from Govee Developer Portal

govee_light_automation:
  api_key: YOUR_GOVEE_API_KEY

# Optional: You can also configure specific devices if needed
# This is not required as the integration will auto-discover devices
light:
  - platform: govee_light_automation
    # Additional device-specific configuration can be added here if needed 